version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin  # TODO: 보안성 강화 필요
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./.docker:/var/lib/mysql
