version: "3"

services:
  application:
    build: ../subprojects/api
    platform: 'linux/amd64'
    ports:
      - '8080:8080'
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    restart: always
