name: Java CI with Gradle

on:
  push:
    branches:
      - cd/20240202/shinyoung
      - main
  pull_request:
    branches:
      - main
env:
  DOCKER_REGISTRY_URL: poten16.kr.ncr.ntruss.com
  DOCKER_IMAGE_NAME: poten16-server
  DOCKER_CONTAINER_NAME: poten16-server
  POTEN16_SERVER_PORT: 8080

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: "Set env.img-tag with short SHA of the commit hash"
        shell: bash
        run: echo "DOCKER_IMAGE_TAG=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Build Docker Image with Gradle
        run: ./gradlew bootBuildImage --imageName=${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Log in to NCP Docker Registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login ${{ env.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

      - name: Push Docker Image to NCP Registry
        run: docker push ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
  deploy-to-ncp:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
    - name: "Set env.img-tag with short SHA of the commit hash"
      shell: bash
      run: echo "DOCKER_IMAGE_TAG=${GITHUB_SHA::6}" >> $GITHUB_ENV

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop ${{ env.DOCKER_CONTAINER_NAME }} || true
          docker rm ${{ env.DOCKER_CONTAINER_NAME }} || true
          docker pull ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} 
          docker run -d --name ${{ DOCKER_CONTAINER_NAME }} -p ${{ POTEN16_SERVER_PORT }}:8080 ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} 
          cd scripts
          chmod +x run_docker.sh
          ./run_docker.sh ${{ env.DOCKER_IMAGE_TAG }}
