name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use secret variable
        run: echo "The secret is ${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
  deploy-to-ncp:
    runs-on: ubuntu-latest
    steps:

    - name: test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "The secret is ${{ secrets.DOCKER_REGISTRY_PASSWORD }}" >> test.txt
          echo "${{ secrets.DOCKER_REGISTRY_USERNAME }}" >> username.txt
